### ISSUE TITLE
Request for version update

### ISSUE THREAD

**Issue by adamsvystun** [rliebz/whoswho#2]
Is it possible to publish new version of the package to pip(with the latest commits to master)?

Particularly I am interested in commit c42e85ff72b470cc558068a7d3be2ea9acafc6c1 that simplifies the re-usability of the package.

**Comment by rliebz** [comment]
Thanks for the interest! I've published the latest `master` as `0.2.0` on pypi.

It's been a few years since I've touched the project or the publishing ecosystem, so let me know if you run into any issues.

Edit: Apparently `master` was broken on Travis, but I had a spare commit from 2016 that looks like it fixed the issue. `0.2.1` should be fine.

**Comment by adamsvystun** [comment]
Thank you very much!
